name: Flash Card App Deployment to Google Cloud Run 
on:
  push:
    branches:
      - FLASHCARD-57-login-page
env:
  REGION: 'asia-southeast1'
  SERVICE: 'flashcard-app'
  NODE_ENV: "production"
  GOOGLE_CLOUD_PROJECT: '${{ secrets.GCP_PROJECT_ID }}'
  GOOGLE_CLOUD_KEYFILE: '${{ secrets.GCP_SA_KEY }}'
  NEXT_PUBLIC_FIREBASE_APIKEY: '${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}'
  NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: '${{ secrets.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN }}'
  NEXT_PUBLIC_FIREBASE_PROJECTID: '${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECTID }}'
  NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: '${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET }}'
  NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: '${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID }}'
  NEXT_PUBLIC_FIREBASE_APPID: '${{ secrets.NEXT_PUBLIC_FIREBASE_APPID }}'
  NEXT_PUBLIC_FIREBASE_MEASUREMENTID: '${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENTID }}'
  NEXT_PUBLIC_LINE_CHANNEL_ID: '${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_ID }}'
  NEXT_PUBLIC_LINE_CHANNEL_SECRET: '${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_SECRET }}'
  NEXT_PUBLIC_LINE_REDIRECT_URI: '${{ secrets.NEXT_PUBLIC_LINE_REDIRECT_URI }}'
  NEXT_PUBLIC_LINE_CODE_VERIFIER: '${{ secrets.NEXT_PUBLIC_LINE_CODE_VERIFIER }}'
  NEXT_PUBLIC_BACKEND_URL: '${{ secrets.NEXT_PUBLIC_BACKEND_URL }}'


jobs:

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
     
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |-
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
   
      - name: Create env file
        run: |
          touch .env
          echo REGION=${{ env.REGION }} >> .env
          echo SERVICE=${{ env.SERVICE }} >> .env
          echo GOOGLE_CLOUD_PROJECT=${{ env.GOOGLE_CLOUD_PROJECT }} >> .env
          echo NEXT_PUBLIC_NODE_ENV=${{ env.NODE_ENV }} >> .env
          echo GOOGLE_CLOUD_KEYFILE=${{ env.GOOGLE_CLOUD_KEYFILE }} >> .env
          echo NEXT_PUBLIC_FIREBASE_APIKEY=${{ env.NEXT_PUBLIC_FIREBASE_APIKEY }} >> .env
          echo NEXT_PUBLIC_FIREBASE_AUTHDOMAIN=${{ env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN }} >> .env
          echo NEXT_PUBLIC_FIREBASE_PROJECTID=${{ env.NEXT_PUBLIC_FIREBASE_PROJECTID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_STORAGEBUCKET=${{ env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET }} >> .env
          echo NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID=${{ env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_APPID=${{ env.NEXT_PUBLIC_FIREBASE_APPID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_MEASUREMENTID=${{ env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID }} >> .env
          echo NEXT_PUBLIC_LINE_CHANNEL_ID=${{ env.NEXT_PUBLIC_LINE_CHANNEL_ID }} >> .env
          echo NEXT_PUBLIC_LINE_CHANNEL_SECRET=${{ env.NEXT_PUBLIC_LINE_CHANNEL_SECRET }} >> .env
          echo NEXT_PUBLIC_LINE_REDIRECT_URI=${{ env.NEXT_PUBLIC_LINE_REDIRECT_URI }} >> .env
          echo NEXT_PUBLIC_LINE_CODE_VERIFIER=${{ env.NEXT_PUBLIC_LINE_CODE_VERIFIER }} >> .env
          echo NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }} >> .env
          cat .env

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          
           
            